# Generated by Django 4.0.2 on 2023-01-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation',
            name='mesg',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
