# Generated by Django 4.0.2 on 2023-02-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0002_alter_motivation_mesg'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationAndOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('title', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
