# Generated by Django 4.0.2 on 2023-02-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0004_churchgallery_churchprograms_imagegallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchprograms',
            old_name='date_paid',
            new_name='eventDate',
        ),
    ]
