# Generated by Django 4.0.2 on 2023-02-26 11:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0005_rename_date_paid_churchprograms_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
