# Generated by Django 4.0.2 on 2023-02-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0006_imagegallery_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='title',
        ),
    ]
