# Generated by Django 4.0.2 on 2023-02-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0007_remove_imagegallery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='eventImg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_church', to='programm.churchgallery'),
        ),
    ]
