# Generated by Django 4.0.2 on 2023-02-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0008_alter_imagegallery_eventimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='eventImg',
        ),
        migrations.DeleteModel(
            name='ChurchGallery',
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
    ]
