# Generated by Django 4.0.2 on 2023-02-26 13:16

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0009_remove_imagegallery_eventimg_delete_churchgallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('eventDate', models.DateTimeField(blank=True, null=True)),
                ('img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pics')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('eventImg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_church', to='programm.churchgallery')),
            ],
            options={
                'verbose_name_plural': 'Image Gallery',
            },
        ),
    ]
