# Generated by Django 4.0.2 on 2023-03-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0010_churchgallery_imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
            ],
        ),
    ]
