# Generated by Django 4.0.2 on 2023-03-05 23:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0011_pastors'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastors',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
