# Generated by Django 4.0.2 on 2023-05-26 05:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0013_alter_churchgallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('timing', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
