# Generated by Django 4.0.2 on 2023-06-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0014_upcomingevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
