# Generated by Django 4.0.2 on 2023-04-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('detail_1', models.CharField(blank=True, max_length=500, null=True)),
                ('detail_2', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Growth Track',
                'ordering': ['-startDate'],
            },
        ),
        migrations.CreateModel(
            name='GrowthTrackEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Growth Track Event',
                'ordering': ['-startDate'],
            },
        ),
    ]
