# Generated by Django 4.0.2 on 2023-04-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthtrack',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
